# Generated by Django 3.2.8 on 2022-09-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=20, unique=True, verbose_name='name')),
                ('first_name', models.TextField(max_length=30, verbose_name='name')),
                ('last_name', models.TextField(max_length=30, verbose_name='surename')),
                ('email_addr', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
